# Generated by Django 5.1.3 on 2024-11-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pijama',
            name='talla',
            field=models.CharField(max_length=3),
        ),
    ]
