# Generated by Django 5.1.3 on 2024-11-05 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicio', '0002_alter_pijama_talla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='votacion',
            field=models.ManyToManyField(related_name='votaciones_pijamas', through='ejercicio.Votaciones', to='ejercicio.pijama'),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_cliente', to='ejercicio.cliente'),
        ),
        migrations.AlterField(
            model_name='votaciones',
            name='puntuacion',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=1),
        ),
    ]
