# Generated by Django 5.1.3 on 2024-11-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicio', '0003_alter_cliente_votacion_alter_cuentabancaria_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votaciones',
            name='puntuacion',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3'),
        ),
    ]
